services:
    rk_eventphotos_module.link_container:
        class: RK\EventPhotosModule\Container\LinkContainer
        arguments:
            - "@translator.default"
            - "@router"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@rk_eventphotos_module.controller_helper"
        tags:
            - { name: zikula.link_container }
